### ISSUE TITLE
Setup unit testing

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/teloscan#141]
## Overview
We should have unit testing set up to help detect breaking changes and catch errors/edge cases during development

## Acceptance criteria
- add suggested vue3 framework/lib
- ensure pre-push hook includes running unit tests

## Tasks

- [x] Set the framework
- [x] Successfully run current tests
- [x] Fix any breaking tests that already exist
- [x] Ensure pre-push hook includes running unit tests
