### ISSUE TITLE
Add ERC1155 NFT token support

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#183]
# Description

Add ERC1155 to Teloscan, like ERC721 & ERC20 implementations

# Tasks

- [ ] Show transfers on transaction page's general tab
- [ ] Show transfers on transaction page's logs page
- [ ] Include the ERC1155 transfers to the NFTs
- [ ] Rename the tab to include ERC1155
- [ ] Add a badge to indicate if the transaction is ERC1155 or not
- [ ] Show a thumbnail image next to the transaction

**Comment by karynemayer** [comment]
@tomtomcrypto do we need a separate tab for the ERC1155? From a user looking for a specific NFT perspective, a way to see all your NFTs consolidated is probably the best approach. If we could do the same for the transfers that would be beneficial.

**Comment by tomtomcrypto** [comment]
@karynemayer We could probably merge it there yes. I've yet to look at how to parse transfers for ERC1155 but shouldn't be much different.

**Comment by tomtomcrypto** [comment]
etherscan does it in a separate tab tho
