### ISSUE TITLE
Improve and document unit tests best practices

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#203]
## Overview

We want to have best practices for unit testing well documented. The goal of this issue is to create one good example of this and the documentation with the guidelines.

## Acceptance criteria

- Improve at least one component testing
- Define unit testing best practices that will be adopted
- Document best practices
- Exemplify best practices with an existing component
- Include bad examples as well

## Tasks

- [ ] Define best practices for unit tests
- [ ] Review the chosen best practices with the team in a meeting
- [ ] Create the document with good and bad examples of the good practices
- [ ] Create the chosen component tests
