### ISSUE TITLE
Improve currency amount display

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#207]
# Description

Currently if the amount is < 0.0001 we show 0

# Tasks

- [x] Show total like on Etherscan with all decimal places
- [x] Turn transaction value to wei on click
- [x] Keep fixed decimal places for staking pages

# Acceptance

Amount shows full value expect on staking pages
