### ISSUE TITLE
Rename "claim" to "withdraw" on the staking page

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#233]
## Description

Currently the staking page uses the word "claim" 
We should replace it with the word "withdraw"

## Task

- [x] Replace "claim" & "claimable" on the stake page  by "withdraw" & "withdrawable"
- [x] Change the names of the component files to match

## Acceptance

- [x] Users navigating to the stake page will see a "Withdraw" tab with a "Withdraw TLOS" button and all instances of "claim" & "claimable" are replaced by "withdraw" & "withdrawable"

**Comment by EJSG** [comment]
We should also change the names of the component files to match
