### ISSUE TITLE
Header re-design

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#274]
## Overview
We want to re-design the header so it will provide all features both on desktop and mobile (currently doesn't have search bar on mobile).

## Acceptance Criteria
- Header should contain search bar
- Header should contain contain sign in button
- Menu should contain light / dark theme toggler inside the dropdown
- When changing theme, dropdown should not close
- Menu should contain stake Telos
- Menu should contain RPC endpoints link
- Menu should contain Telos monitor link
- Menu should contain testnet toggle
- Consider anonymous and logged in state on all pages

## Tasks
- [x] Meet to discuss previous designs
- [x] [Figma design](https://www.figma.com/file/MlvrttmWn1e27uITFsIrBg/v1.0.0?node-id=1%3A15&t=Ii57rD6PE1142C6P-1) must be provided 
- [ ] Design requires approval
- [ ] Implementation:
    - [x] create general responsive layout
        - [x] sticky with slight drop shadow
        - [x] mobile
            - [x] menu icon 
            - [x] search icon, search component
            - [x] teloscan icon
        - [x] desktop
            - [x] logo with label
            - [x] search bar
            - [x] conditional logon status
            - [x] second level (i.e. horizontal menu) with links
    - [x] login status component
        - [x] v-if logged in
        - [x] account icon
        - [x] shortened address
        - [x] view address button w/ tooltip on hover
        - [x] copy address button w/ tooltip on hover
    - [x] advanced menu component
        - [x] investigate available quasar components
        - [x] mobile: expandable list, block display, indented items
        - [x] desktop: toggleable dropdown, items not indented
    - [x] menu (not a separate component because of advanced RWD flex layout)
        - [x] mobile: vertical stacking, include login status
        - [x] desktop: 
        - [x] advanced dropdown
    - [x] search bar
        - [x] enter key or click/tap on search icon should execute search
        - [x] mobile: clickaway functionality for search input (input should hide if user clicks outside of it) 
        - [x] re-style to match expanded search bar design
        - [x] remove search bar from home page table header - also search for other usages of search component
        - [x] remove ticker text, switch to static placeholder
        - [x] mobile: test search input focus on iOS - iOS may disallow focusing an input after clicking search icon
    - [x] audit "ConnectButton" usage (e.g. it is referred to in staking for logged out users)
    - [x] refactor login modal out of ConnectButton to make it accessible anywhere
    - [x] dark and light styling for everything above

## Notes
These changes also solve:
https://github.com/telosnetwork/teloscan/issues/262
https://github.com/telosnetwork/teloscan/issues/260
