### ISSUE TITLE
Refactor staking page to show interface even if logged out / logged on native

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#276]
## Description

Currently the staking page only shows an error message if the user isn't logged into EVM. This was a fix to the infini load bug we had.
We want the interface to show up no matter the status of the user, and have an error message warning him on top if he is logged in on Native.

## Tasks

- [ ] Feed a signing provider if the user is logged into native
- [ ] Refactor error message to show up on top of the interface

## Acceptance

- [ ] Users can navigate to the staking page and see the interface no matter their login status
- [ ] Users logged into native can see an error message warning them that they need to log into EVM to use staking
