### ISSUE TITLE
Header internationalization

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#313]
## Overview
The new header needs to include the language switcher and be translated.

## Acceptance criteria
- add i18n for header text
- Design language switcher
- Implement language switcher

## Tasks
- [x] add i18n to existing header text
- [x] add language switcher for mobile and desktop
- [x] add i18n for new language switcher
- [ ] create ticket to update portuguese translations to match https://github.com/telosnetwork/teloscan/pull/318

**Comment by Viterbo** [comment]
@EJSG, you may want to wait until [this PR](https://github.com/telosnetwork/teloscan/pull/316) is solved because it includes al text translations of the new header.
