### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/teloscan#385]
## Description

PR #368 add a `components.no_balances_found` string
Translations are needed for every language but english or french

## Tasks

- [ ] Translate `components.no_balances_found` to portuguese
- [ ] Translate `components.no_balances_found` to spanish
- [ ] Translate `components.no_balances_found` to dutch
