### ISSUE TITLE
Block Navigation

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#392]
## Overview
Ability to navigate sequential blocks directly on Block Page
![image](https://user-images.githubusercontent.com/6848910/231665791-70dc8155-4956-492e-91fe-46e0afaea203.png)

## Acceptance Criteria

- on block page view, left and right arrow buttons per design
- clicking left arrow button loads previous block's data (url param, block data, table data, and block number update)
- clicking right arrow button loads previous block's data (url param, block data,  table, and block number update)

## Tasks

- [x] add buttons with arrow icons and box border
- [x] add router methods to update params
- [x] add watcher on route params to trigger update
- [x] filter watcher on tx table to trigger refresh
