### ISSUE TITLE
CloudFlare migration

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/teloscan#440]
## Overview
Migrate from Netlify to CloudFlare

## Links
https://github.com/cloudflare/pages-action

## Acceptance Criteria

- [ ] CI/CD from github into cloudflare, auto push to both mainnet and testnet URLs
  - [ ] Include a branch deploy URL on mainnet/testnet for dev branch
  - [ ] Auto create & remove of deploy preview for both mainnet and testnet ENV vars for all active/open pull requests
- [ ] Maintain URL/branch/preview strategy we currently have

## Tasks/Design

- One Cloudflare Pages project for mainnet, one for testnet
- Each project behaves quite similar except for ENV vars, they are both "production" but just configured for different network.  Each project will get:
  - A separate project record in cloudflare, and project id, etc...
  - A production URL, teloscan.io or testnet.teloscan.io
  - A cloudflare URL, teloscan.pages.dev or teloscan-test.pages.dev, under this URL is where each project's branch and deploy preview URLs will live

- On push where branch is master or dev:
  -
