### ISSUE TITLE
Update Branding

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/teloscan#484]
**Description**
~~Update theme using new logos & colors~~
Update: logos have been updated, only need theme/colors update

**Tasks**

- [x] Update Teloscan logo 
- [x] Teloscan logo - favicon
- [x] sTLOS logo
- [x] TLOS logo - reference
- [ ] Update colors/theme

**Blockers**

- [ ] Teloscan text logo svg
- [ ] Theme colors

**Resources**
https://www.telos.net/community-resources
https://github.com/telosnetwork/token-list
