### ISSUE TITLE
Ticket out teloscan repo updates

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/teloscan#92]
These are misc. items which I believe are needed for Teloscan
Deliverable to be prioritized & categorized Issues - no code changes

Including but not limited to:
- [x] ~ticket out all extant TODOs, replace TODO with ticket URL~ #134
- [x] ~update linting rules~ #127
- [x] standardize / unify file types
    - ~pug -> vue html~ #128
    - ~sass -> scss~ #129
    - ~vue sfc structure template > script > style~ #130
- [x] ~defined text styles~ #131
- [x] scss spacer variables to match quasar's system (eg. `q-pa-md` => `$spacer-md`) #135
- [x] ~remove/replace quasar overrides (eg. `.shadow-2 { box-shadow: none !important }` from `app.sass`)~ #136
- [x] ~consolidate app colors~ #132
- [x] ~component styles cleanup~ #137
    - [x] ~namespace selectors using BEM~
    - [x] ~remove/replace all inline styles~
    - [x] ~remove `scoped` styles, track down all overly-specific selectors which break after this is removed~
- [x] ~switch `margin-top`s with `margin-bottom`s (and `padding-`) on preceding elements where possible~ #126 
- [x] general directory structure & organization #138
- [x] ~documentation~ #139
    - ~make docs directory~
    - ~update repo first time setup~
    - ~git / contribution workflow, deployment info incl. netlify preview~
    - ~styling basics (refer to other points in this ticket)~
    - ~unit testing~
    - ~require JSdocs ([eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc))~
- [x] ~github~ #140
        - ~issue naming & labeling & templates~
        - ~PR template~
        - ~pre-push hooks for lint & possibly build~
        - ~assignees~
- [x] setup unit testing
